PARCIAL 2 LIMPIEZA DE DATOS

[GITHUB](https://github.com/1706712022/etl-data-pipeline1706712022.git)

In [ ]:
import pandas as pd

In [ ]:
url = "https://raw.githubusercontent.com/1706712022/etl-data-pipeline1706712022/refs/heads/main/data/raw/E_movimientos.csv"

In [ ]:
df_mov = pd.read_csv(url)
print("Dataset Cargado Correctamente")

Dataset Cargado Correctamente

In [ ]:
df_mov.head()

  id_movimiento id_inventario tipo_movimiento       fecha cantidad_movimiento
0       MOV9000       INV5000          ajuste  2025-03-05                  15
1       MOV9001       INV5122          ajuste  2024-03-06              73 uds
2       MOV9002       INV5019          salida  2024-05-27                  30
3       MOV9003       INV5110         entrada  2025-01-16                  44
4       MOV9004       INV5152         entrada  2024-08-28                  55

In [ ]:
print ("Primeras filas del Dataset");
df_mov.head()

Primeras filas del Dataset

  id_movimiento id_inventario tipo_movimiento       fecha cantidad_movimiento
0       MOV9000       INV5000          ajuste  2025-03-05                  15
1       MOV9001       INV5122          ajuste  2024-03-06              73 uds
2       MOV9002       INV5019          salida  2024-05-27                  30
3       MOV9003       INV5110         entrada  2025-01-16                  44
4       MOV9004       INV5152         entrada  2024-08-28                  55

In [ ]:
print("Data Types and Non-Null Counts:")
df_mov.info()

print("\nMissing Values per Column:")
print(df_mov.isnull().sum())

print("\nDescriptive Statistics:")
df_mov.describe()

Data Types and Non-Null Counts:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 226 entries, 0 to 225
Data columns (total 5 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id_movimiento        226 non-null    object
 1   id_inventario        220 non-null    object
 2   tipo_movimiento      226 non-null    object
 3   fecha                221 non-null    object
 4   cantidad_movimiento  222 non-null    object
dtypes: object(5)
memory usage: 9.0+ KB

Missing Values per Column:
id_movimiento          0
id_inventario          6
tipo_movimiento        0
fecha                  5
cantidad_movimiento    4
dtype: int64

Descriptive Statistics:

,id_movimiento,id_inventario,tipo_movimiento,fecha,cantidad_movimiento
count,226,220,226,221,222
unique,220,124,8,183,83
top,MOV9086,INV5107,traslado,2025-06-13,3
freq,2,5,63,3,8

In [ ]:
df_mov.columns = [col.lower().replace(' ', '_') for col in df_mov.columns]
print("Column names standardized:")
df_mov.head()

Column names standardized:

  id_movimiento id_inventario tipo_movimiento       fecha cantidad_movimiento
0       MOV9000       INV5000          ajuste  2025-03-05                  15
1       MOV9001       INV5122          ajuste  2024-03-06              73 uds
2       MOV9002       INV5019          salida  2024-05-27                  30
3       MOV9003       INV5110         entrada  2025-01-16                  44
4       MOV9004       INV5152         entrada  2024-08-28                  55

In [ ]:
df_mov['cantidad_movimiento'] = df_mov['cantidad_movimiento'].astype(str).str.replace(r'\D', '', regex=True)
df_mov['cantidad_movimiento'] = pd.to_numeric(df_mov['cantidad_movimiento'], errors='coerce')

print("Data Types after cleaning 'cantidad_movimiento':")
df_mov.info()

print("\nFirst few rows after cleaning 'cantidad_movimiento':")
df_mov.head()

Data Types after cleaning 'cantidad_movimiento':
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 226 entries, 0 to 225
Data columns (total 5 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id_movimiento        226 non-null    object
 1   id_inventario        220 non-null    object
 2   tipo_movimiento      226 non-null    object
 3   fecha                221 non-null    object
 4   cantidad_movimiento  222 non-null    float64
dtypes: float64(1), object(4)
memory usage: 9.0+ KB

First few rows after cleaning 'cantidad_movimiento':

  id_movimiento id_inventario tipo_movimiento       fecha  cantidad_movimiento
0       MOV9000       INV5000          ajuste  2025-03-05                 15.0
1       MOV9001       INV5122          ajuste  2024-03-06                 73.0
2       MOV9002       INV5019          salida  2024-05-27                 30.0
3       MOV9003       INV5110         entrada  2025-01-16                 44.0
4       MOV9004       INV5152         entrada  2024-08-28                 55.0

In [ ]:
rejects_df_mov = df_mov[df_mov['cantidad_movimiento'].isna()].copy()
curated_df_mov = df_mov[df_mov['cantidad_movimiento'].notna()].copy()

print(f"Shape of rejects_df_mov: {rejects_df_mov.shape}")
print(f"Shape of curated_df_mov: {curated_df_mov.shape}")

Shape of rejects_df_mov: (4, 5)
Shape of curated_df_mov: (222, 5)

In [ ]:
print("df_mov - Primeras 5 filas:")
df_mov.head()

print("\ndf_mov - Información:")
df_mov.info()

print("\ncurated_df_mov - Primeras 5 filas:")
curated_df_mov.head()

print("\ncurated_df_mov - Información:")
curated_df_mov.info()

print("\nrejects_df_mov - Primeras 5 filas:")
rejects_df_mov.head()

print("\nrejects_df_mov - Información:")
rejects_df_mov.info()

df_mov - Primeras 5 filas:

df_mov - Información:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 226 entries, 0 to 225
Data columns (total 5 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id_movimiento        226 non-null    object
 1   id_inventario        220 non-null    object
 2   tipo_movimiento      226 non-null    object
 3   fecha                221 non-null    object
 4   cantidad_movimiento  222 non-null    float64
dtypes: float64(1), object(4)
memory usage: 9.0+ KB

curated_df_mov - Primeras 5 filas:

curated_df_mov - Información:
<class 'pandas.core.frame.DataFrame'>
Index: 222 entries, 0 to 225
Data columns (total 5 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id_movimiento        222 non-null    object
 1   id_inventario        217 non-null    object
 2   tipo_movimiento      222 non-null    object
 3   fecha                217 non-null    object
 4   cantidad_movimiento  222 non-null    float64
dtypes: float64(1), object(4)
memory usage: 10.4+ KB

rejects_df_mov - Primeras 5 filas:

rejects_df_mov - Información:
<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, 22 to 217
Data columns (total 5 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id_movimiento        4 non-null      object
 1   id_inventario        3 non-null      object
 2   tipo_movimiento      4 non-null      object
 3   fecha                4 non-null      object
 4   cantidad_movimiento  0 non-null      float64
dtypes: float64(1), object(4)
memory usage: 192.0+ bytes

In [ ]:
curated_df_mov['fecha'] = pd.to_datetime(curated_df_mov['fecha'], errors='coerce')

print("curated_df_mov - Data types after converting 'fecha' column:")
curated_df_mov.info()

print("\ncurated_df_mov - Primeras 5 filas después de convertir 'fecha':")
curated_df_mov.head()

curated_df_mov - Data types after converting 'fecha' column:
<class 'pandas.core.frame.DataFrame'>
Index: 222 entries, 0 to 225
Data columns (total 5 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id_movimiento        222 non-null    object
 1   id_inventario        217 non-null    object
 2   tipo_movimiento      222 non-null    object
 3   fecha                203 non-null    datetime64[ns]
 4   cantidad_movimiento  222 non-null    float64
dtypes: datetime64[ns](1), float64(1), object(3)
memory usage: 10.4+ KB

curated_df_mov - Primeras 5 filas después de convertir 'fecha':

  id_movimiento id_inventario tipo_movimiento      fecha  cantidad_movimiento
0       MOV9000       INV5000          ajuste 2025-03-05                 15.0
1       MOV9001       INV5122          ajuste 2024-03-06                 73.0
2       MOV9002       INV5019          salida 2024-05-27                 30.0
3       MOV9003       INV5110         entrada 2025-01-16                 44.0
4       MOV9004       INV5152         entrada 2024-08-28                 55.0

In [ ]:
print("\nMissing values in curated_df_mov before dropping:")
print(curated_df_mov[['id_inventario', 'fecha']].isnull().sum())

curated_df_mov.dropna(subset=['id_inventario', 'fecha'], inplace=True)

print("\nShape of curated_df_mov after dropping rows with missing 'id_inventario' or 'fecha':", curated_df_mov.shape)
print("\ncurated_df_mov - Information after dropping nulls:")
curated_df_mov.info()

Missing values in curated_df_mov before dropping:
id_inventario     5
fecha            19
dtype: int64

Shape of curated_df_mov after dropping rows with missing 'id_inventario' or 'fecha': (198, 5)

curated_df_mov - Information after dropping nulls:
<class 'pandas.core.frame.DataFrame'>
Index: 198 entries, 0 to 225
Data columns (total 5 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id_movimiento        198 non-null    object
 1   id_inventario        198 non-null    object
 2   tipo_movimiento      198 non-null    object
 3   fecha                198 non-null    datetime64[ns]
 4   cantidad_movimiento  198 non-null    float64
dtypes: datetime64[ns](1), float64(1), object(3)
memory usage: 9.3+ KB

In [ ]:
print("rejects_df_mov - Todas las filas para inspección:")
print(rejects_df_mov)

rejects_df_mov - Todas las filas para inspección:
    id_movimiento id_inventario tipo_movimiento       fecha  \
22        MOV9022       INV9999        traslado  2025-03-18
110       MOV9110           NaN          ajuste  2024-09-28
117       MOV9117       INV5017          salida  2024-11-01
217       MOV9217       INV5107         entrada  2024-10-16

     cantidad_movimiento
22                   NaN
110                  NaN
117                  NaN
217                  NaN

In [ ]:
#SEPARACIÓN
inventario_curated = df_mov[df_mov['motivo_rechazo'] == ""].copy()
inventario_rejects = df_mov[df_mov['motivo_rechazo'] != ""].copy()

KeyError: 'motivo_rechazo'

# Task
The `KeyError: 'motivo_rechazo'` occurred because the column `'motivo_rechazo'` does not exist in `df_mov`.

Currently, `df_mov`, `curated_df_mov`, and `rejects_df_mov` all contain the following columns: `id_movimiento`, `id_inventario`, `tipo_movimiento`, `fecha`, and `cantidad_movimiento`.

`curated_df_mov` was created by selecting rows from `df_mov` where `cantidad_movimiento` is not null, and `rejects_df_mov` contains rows where `cantidad_movimiento` is null. Missing values in `id_inventario` and `fecha` have also been dropped from `curated_df_mov`.

To proceed, please clarify how you intend to create or define the `'motivo_rechazo'` column. Do you want to:
1. Create a new column named `'motivo_rechazo'` in `df_mov` (or `curated_df_mov`/`rejects_df_mov`) based on certain criteria?
2. Use an existing column to define criteria for further splitting `curated_df_mov` or `rejects_df_mov`?

## Explain KeyError

### Subtask:
Explain that 'motivo_rechazo' column does not exist in df_mov.

## Explain KeyError

### Subtask:
Explain that 'motivo_rechazo' column does not exist in df_mov.

#### Instructions
The `KeyError: 'motivo_rechazo'` occurred because the column 'motivo_rechazo' was not found in the `df_mov` DataFrame. This column needs to be created or defined before it can be used for filtering or other operations. The previous steps only created `rejects_df_mov` and `curated_df_mov` based on `cantidad_movimiento` null values, and no 'motivo_rechazo' column was added to `df_mov`.

## Contextualize DataFrame state

### Subtask:
Describe the current columns available in `df_mov`, `curated_df_mov`, and `rejects_df_mov`.

```markdown
Currently, `df_mov`, `curated_df_mov`, and `rejects_df_mov` all contain the following columns: `id_movimiento`, `id_inventario`, `tipo_movimiento`, `fecha`, and `cantidad_movimiento`.

`curated_df_mov` was derived from `df_mov` by first keeping rows where `cantidad_movimiento` was not null, and subsequently dropping rows that had null values in either the `id_inventario` or `fecha` columns.

`rejects_df_mov` contains the rows from `df_mov` where the `cantidad_movimiento` was originally null (before the `astype(str).str.replace` and `pd.to_numeric` operations).
```

Currently, `df_mov`, `curated_df_mov`, and `rejects_df_mov` all contain the following columns: `id_movimiento`, `id_inventario`, `tipo_movimiento`, `fecha`, and `cantidad_movimiento`.

`curated_df_mov` was derived from `df_mov` by first keeping rows where `cantidad_movimiento` was not null, and subsequently dropping rows that had null values in either the `id_inventario` or `fecha` columns.

`rejects_df_mov` contains the rows from `df_mov` where the `cantidad_movimiento` was originally null (before the `astype(str).str.replace` and `pd.to_numeric` operations).

Currently, `df_mov`, `curated_df_mov`, and `rejects_df_mov` all contain the following columns: `id_movimiento`, `id_inventario`, `tipo_movimiento`, `fecha`, and `cantidad_movimiento`.

`curated_df_mov` was derived from `df_mov` by first keeping rows where `cantidad_movimiento` was not null, and subsequently dropping rows that had null values in either the `id_inventario` or `fecha` columns.

`rejects_df_mov` contains the rows from `df_mov` where the `cantidad_movimiento` was originally null (before the `astype(str).str.replace` and `pd.to_numeric` operations).

Currently, `df_mov`, `curated_df_mov`, and `rejects_df_mov` all contain the following columns: `id_movimiento`, `id_inventario`, `tipo_movimiento`, `fecha`, and `cantidad_movimiento`.

`curated_df_mov` was derived from `df_mov` by first keeping rows where `cantidad_movimiento` was not null, and subsequently dropping rows that had null values in either the `id_inventario` or `fecha` columns.

`rejects_df_mov` contains the rows from `df_mov` where the `cantidad_movimiento` was originally null (before the `astype(str).str.replace` and `pd.to_numeric` operations).

Currently, `df_mov`, `curated_df_mov`, and `rejects_df_mov` all contain the following columns: `id_movimiento`, `id_inventario`, `tipo_movimiento`, `fecha`, and `cantidad_movimiento`.

`curated_df_mov` was derived from `df_mov` by first keeping rows where `cantidad_movimiento` was not null, and subsequently dropping rows that had null values in either the `id_inventario` or `fecha` columns.

`rejects_df_mov` contains the rows from `df_mov` where the `cantidad_movimiento` was originally null (before the `astype(str).str.replace` and `pd.to_numeric` operations).

Currently, `df_mov`, `curated_df_mov`, and `rejects_df_mov` all contain the following columns: `id_movimiento`, `id_inventario`, `tipo_movimiento`, `fecha`, and `cantidad_movimiento`.

`curated_df_mov` was derived from `df_mov` by first keeping rows where `cantidad_movimiento` was not null, and subsequently dropping rows that had null values in either the `id_inventario` or `fecha` columns.

`rejects_df_mov` contains the rows from `df_mov` where the `cantidad_movimiento` was originally null (before the `astype(str).str.replace` and `pd.to_numeric` operations).

```markdown
Currently, `df_mov`, `curated_df_mov`, and `rejects_df_mov` all contain the following columns: `id_movimiento`, `id_inventario`, `tipo_movimiento`, `fecha`, and `cantidad_movimiento`.

`curated_df_mov` was derived from `df_mov` by first keeping rows where `cantidad_movimiento` was not null, and subsequently dropping rows that had null values in either the `id_inventario` or `fecha` columns.

`rejects_df_mov` contains the rows from `df_mov` where the `cantidad_movimiento` was originally null (before the `astype(str).str.replace` and `pd.to_numeric` operations).
```

Currently, `df_mov`, `curated_df_mov`, and `rejects_df_mov` all contain the following columns: `id_movimiento`, `id_inventario`, `tipo_movimiento`, `fecha`, and `cantidad_movimiento`.

`curated_df_mov` was derived from `df_mov` by first keeping rows where `cantidad_movimiento` was not null, and subsequently dropping rows that had null values in either the `id_inventario` or `fecha` columns.

`rejects_df_mov` contains the rows from `df_mov` where the `cantidad_movimiento` was originally null (before the `astype(str).str.replace` and `pd.to_numeric` operations).

Currently, `df_mov`, `curated_df_mov`, and `rejects_df_mov` all contain the following columns: `id_movimiento`, `id_inventario`, `tipo_movimiento`, `fecha`, and `cantidad_movimiento`.

`curated_df_mov` was derived from `df_mov` by first keeping rows where `cantidad_movimiento` was not null, and subsequently dropping rows that had null values in either the `id_inventario` or `fecha` columns.

`rejects_df_mov` contains the rows from `df_mov` where the `cantidad_movimiento` was originally null (before the `astype(str).str.replace` and `pd.to_numeric` operations).

Currently, `df_mov`, `curated_df_mov`, and `rejects_df_mov` all contain the following columns: `id_movimiento`, `id_inventario`, `tipo_movimiento`, `fecha`, and `cantidad_movimiento`.

`curated_df_mov` was derived from `df_mov` by first keeping rows where `cantidad_movimiento` was not null, and subsequently dropping rows that had null values in either the `id_inventario` or `fecha` columns.

`rejects_df_mov` contains the rows from `df_mov` where the `cantidad_movimiento` was originally null (before the `astype(str).str.replace` and `pd.to_numeric` operations).

Currently, `df_mov`, `curated_df_mov`, and `rejects_df_mov` all contain the following columns: `id_movimiento`, `id_inventario`, `tipo_movimiento`, `fecha`, and `cantidad_movimiento`.

`curated_df_mov` was derived from `df_mov` by first keeping rows where `cantidad_movimiento` was not null, and subsequently dropping rows that had null values in either the `id_inventario` or `fecha` columns.

`rejects_df_mov` contains the rows from `df_mov` where the `cantidad_movimiento` was originally null (before the `astype(str).str.replace` and `pd.to_numeric` operations).

Currently, `df_mov`, `curated_df_mov`, and `rejects_df_mov` all contain the following columns: `id_movimiento`, `id_inventario`, `tipo_movimiento`, `fecha`, and `cantidad_movimiento`.

`curated_df_mov` was derived from `df_mov` by first keeping rows where `cantidad_movimiento` was not null, and subsequently dropping rows that had null values in either the `id_inventario` or `fecha` columns.

`rejects_df_mov` contains the rows from `df_mov` where the `cantidad_movimiento` was originally null (before the `astype(str).str.replace` and `pd.to_numeric` operations).

Currently, `df_mov`, `curated_df_mov`, and `rejects_df_mov` all contain the following columns: `id_movimiento`, `id_inventario`, `tipo_movimiento`, `fecha`, and `cantidad_movimiento`.

`curated_df_mov` was derived from `df_mov` by first keeping rows where `cantidad_movimiento` was not null, and subsequently dropping rows that had null values in either the `id_inventario` or `fecha` columns.

`rejects_df_mov` contains the rows from `df_mov` where the `cantidad_movimiento` was originally null (before the `astype(str).str.replace` and `pd.to_numeric` operations).

Currently, `df_mov`, `curated_df_mov`, and `rejects_df_mov` all contain the following columns: `id_movimiento`, `id_inventario`, `tipo_movimiento`, `fecha`, and `cantidad_movimiento`.

`curated_df_mov` was derived from `df_mov` by first keeping rows where `cantidad_movimiento` was not null, and subsequently dropping rows that had null values in either the `id_inventario` or `fecha` columns.

`rejects_df_mov` contains the rows from `df_mov` where the `cantidad_movimiento` was originally null (before the `astype(str).str.replace` and `pd.to_numeric` operations).

Currently, `df_mov`, `curated_df_mov`, and `rejects_df_mov` all contain the following columns: `id_movimiento`, `id_inventario`, `tipo_movimiento`, `fecha`, and `cantidad_movimiento`.

`curated_df_mov` was derived from `df_mov` by first keeping rows where `cantidad_movimiento` was not null, and subsequently dropping rows that had null values in either the `id_inventario` or `fecha` columns.

`rejects_df_mov` contains the rows from `df_mov` where the `cantidad_movimiento` was originally null (before the `astype(str).str.replace` and `pd.to_numeric` operations).

## Suggest next steps for user

### Subtask:
Ask the user to clarify how to create or define the 'motivo_rechazo' column, either by creating a new column or by using an existing column for splitting.

## Summary:

### Q&A
To proceed, it is necessary to clarify how the `motivo_rechazo` column should be created or defined. The available options are:
1.  Create a new column named `motivo_rechazo` in `df_mov` (or `curated_df_mov`/`rejects_df_mov`) based on specific criteria.
2.  Utilize an existing column to establish criteria for further splitting `curated_df_mov` or `rejects_df_mov`.

### Data Analysis Key Findings
*   A `KeyError: 'motivo_rechazo'` occurred because the column `motivo_rechazo` does not exist in the `df_mov` DataFrame.
*   Currently, `df_mov`, `curated_df_mov`, and `rejects_df_mov` all contain the columns: `id_movimiento`, `id_inventario`, `tipo_movimiento`, `fecha`, and `cantidad_movimiento`.
*   `curated_df_mov` was derived from `df_mov` by selecting rows where `cantidad_movimiento` is not null and then dropping rows with null values in `id_inventario` or `fecha`.
*   `rejects_df_mov` comprises rows from `df_mov` where `cantidad_movimiento` was originally null.

### Insights or Next Steps
*   The next step requires user input to define the logic for creating or mapping the `motivo_rechazo` column.
*   Based on the user's decision, the appropriate method (e.g., creating a new column with specific criteria or re-purposing an existing column) will be implemented to resolve the missing `motivo_rechazo` column.